// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: port.proto

package port

import (
	common "github.com/QFEX-org/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddOrderRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Symbol        string                  `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          common.OrderDirection   `protobuf:"varint,2,opt,name=side,proto3,enum=common.OrderDirection" json:"side,omitempty"`
	Type          common.OrderType        `protobuf:"varint,3,opt,name=type,proto3,enum=common.OrderType" json:"type,omitempty"`
	TimeInForce   common.OrderTimeInForce `protobuf:"varint,4,opt,name=time_in_force,json=timeInForce,proto3,enum=common.OrderTimeInForce" json:"time_in_force,omitempty"`
	Quantity      float64                 `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`                                      // Order quantity
	Price         float64                 `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`                                            // Order price (optional for MARKET)
	ClientOrderId *string                 `protobuf:"bytes,7,opt,name=client_order_id,json=clientOrderId,proto3,oneof" json:"client_order_id,omitempty"` // Client order ID. Autogenerated if not sent
	Timestamp     *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                      // Unix timestamp in nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderRequest) Reset() {
	*x = AddOrderRequest{}
	mi := &file_port_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderRequest) ProtoMessage() {}

func (x *AddOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderRequest.ProtoReflect.Descriptor instead.
func (*AddOrderRequest) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{0}
}

func (x *AddOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AddOrderRequest) GetSide() common.OrderDirection {
	if x != nil {
		return x.Side
	}
	return common.OrderDirection(0)
}

func (x *AddOrderRequest) GetType() common.OrderType {
	if x != nil {
		return x.Type
	}
	return common.OrderType(0)
}

func (x *AddOrderRequest) GetTimeInForce() common.OrderTimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return common.OrderTimeInForce(0)
}

func (x *AddOrderRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddOrderRequest) GetClientOrderId() string {
	if x != nil && x.ClientOrderId != nil {
		return *x.ClientOrderId
	}
	return ""
}

func (x *AddOrderRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CancelOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to OrderIdChoice:
	//
	//	*CancelOrderRequest_OrderId
	//	*CancelOrderRequest_ClientOrderId
	OrderIdChoice isCancelOrderRequest_OrderIdChoice `protobuf_oneof:"order_id_choice"`
	Symbol        string                             `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_port_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{1}
}

func (x *CancelOrderRequest) GetOrderIdChoice() isCancelOrderRequest_OrderIdChoice {
	if x != nil {
		return x.OrderIdChoice
	}
	return nil
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		if x, ok := x.OrderIdChoice.(*CancelOrderRequest_OrderId); ok {
			return x.OrderId
		}
	}
	return ""
}

func (x *CancelOrderRequest) GetClientOrderId() string {
	if x != nil {
		if x, ok := x.OrderIdChoice.(*CancelOrderRequest_ClientOrderId); ok {
			return x.ClientOrderId
		}
	}
	return ""
}

func (x *CancelOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type isCancelOrderRequest_OrderIdChoice interface {
	isCancelOrderRequest_OrderIdChoice()
}

type CancelOrderRequest_OrderId struct {
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3,oneof"`
}

type CancelOrderRequest_ClientOrderId struct {
	ClientOrderId string `protobuf:"bytes,2,opt,name=client_order_id,json=clientOrderId,proto3,oneof"`
}

func (*CancelOrderRequest_OrderId) isCancelOrderRequest_OrderIdChoice() {}

func (*CancelOrderRequest_ClientOrderId) isCancelOrderRequest_OrderIdChoice() {}

type ModifyOrderRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Symbol           string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`                                               // Trading pair, e.g., "BTCUSDT"
	OrderId          string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                              // Order ID
	OriginalQuantity float64                `protobuf:"fixed64,3,opt,name=original_quantity,json=originalQuantity,proto3" json:"original_quantity,omitempty"` // Order quantity
	Quantity         float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`                                         // Order quantity
	Price            float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`                                               // Order price
	Side             common.OrderDirection  `protobuf:"varint,6,opt,name=side,proto3,enum=common.OrderDirection" json:"side,omitempty"`
	Timestamp        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                     // Unix timestamp in milliseconds
	UpdateTime       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"` // Unix timestamp in milliseconds
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ModifyOrderRequest) Reset() {
	*x = ModifyOrderRequest{}
	mi := &file_port_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyOrderRequest) ProtoMessage() {}

func (x *ModifyOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyOrderRequest.ProtoReflect.Descriptor instead.
func (*ModifyOrderRequest) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{2}
}

func (x *ModifyOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ModifyOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ModifyOrderRequest) GetOriginalQuantity() float64 {
	if x != nil {
		return x.OriginalQuantity
	}
	return 0
}

func (x *ModifyOrderRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ModifyOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ModifyOrderRequest) GetSide() common.OrderDirection {
	if x != nil {
		return x.Side
	}
	return common.OrderDirection(0)
}

func (x *ModifyOrderRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ModifyOrderRequest) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_port_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOrderRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type SetLeverageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Leverage      float32                `protobuf:"fixed32,2,opt,name=leverage,proto3" json:"leverage,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLeverageRequest) Reset() {
	*x = SetLeverageRequest{}
	mi := &file_port_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLeverageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLeverageRequest) ProtoMessage() {}

func (x *SetLeverageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLeverageRequest.ProtoReflect.Descriptor instead.
func (*SetLeverageRequest) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{4}
}

func (x *SetLeverageRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SetLeverageRequest) GetLeverage() float32 {
	if x != nil {
		return x.Leverage
	}
	return 0
}

func (x *SetLeverageRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type LeveragesPublic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leverages     []*LeveragePublic      `protobuf:"bytes,1,rep,name=leverages,proto3" json:"leverages,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeveragesPublic) Reset() {
	*x = LeveragesPublic{}
	mi := &file_port_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeveragesPublic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeveragesPublic) ProtoMessage() {}

func (x *LeveragesPublic) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeveragesPublic.ProtoReflect.Descriptor instead.
func (*LeveragesPublic) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{5}
}

func (x *LeveragesPublic) GetLeverages() []*LeveragePublic {
	if x != nil {
		return x.Leverages
	}
	return nil
}

func (x *LeveragesPublic) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeveragesPublic) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type LeveragePublic struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol            string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	InitialMargin     float64                `protobuf:"fixed64,3,opt,name=initial_margin,json=initialMargin,proto3" json:"initial_margin,omitempty"`
	MaintenanceMargin float64                `protobuf:"fixed64,4,opt,name=maintenance_margin,json=maintenanceMargin,proto3" json:"maintenance_margin,omitempty"`
	MaxPosition       float64                `protobuf:"fixed64,5,opt,name=max_position,json=maxPosition,proto3" json:"max_position,omitempty"`
	Leverage          string                 `protobuf:"bytes,6,opt,name=leverage,proto3" json:"leverage,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LeveragePublic) Reset() {
	*x = LeveragePublic{}
	mi := &file_port_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeveragePublic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeveragePublic) ProtoMessage() {}

func (x *LeveragePublic) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeveragePublic.ProtoReflect.Descriptor instead.
func (*LeveragePublic) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{6}
}

func (x *LeveragePublic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LeveragePublic) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *LeveragePublic) GetInitialMargin() float64 {
	if x != nil {
		return x.InitialMargin
	}
	return 0
}

func (x *LeveragePublic) GetMaintenanceMargin() float64 {
	if x != nil {
		return x.MaintenanceMargin
	}
	return 0
}

func (x *LeveragePublic) GetMaxPosition() float64 {
	if x != nil {
		return x.MaxPosition
	}
	return 0
}

func (x *LeveragePublic) GetLeverage() string {
	if x != nil {
		return x.Leverage
	}
	return ""
}

type OrderResponse struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	OrderId           string                  `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Symbol            string                  `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Status            common.OrderStatus      `protobuf:"varint,3,opt,name=status,proto3,enum=common.OrderStatus" json:"status,omitempty"`
	Quantity          float64                 `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price             float64                 `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Side              common.OrderDirection   `protobuf:"varint,7,opt,name=side,proto3,enum=common.OrderDirection" json:"side,omitempty"`
	Type              common.OrderType        `protobuf:"varint,8,opt,name=type,proto3,enum=common.OrderType" json:"type,omitempty"`
	TimeInForce       common.OrderTimeInForce `protobuf:"varint,9,opt,name=time_in_force,json=timeInForce,proto3,enum=common.OrderTimeInForce" json:"time_in_force,omitempty"`
	UpdateTime        *timestamppb.Timestamp  `protobuf:"bytes,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	UserId            string                  `protobuf:"bytes,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientOrderId     string                  `protobuf:"bytes,12,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	QuantityRemaining float64                 `protobuf:"fixed64,13,opt,name=quantity_remaining,json=quantityRemaining,proto3" json:"quantity_remaining,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_port_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{7}
}

func (x *OrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderResponse) GetStatus() common.OrderStatus {
	if x != nil {
		return x.Status
	}
	return common.OrderStatus(0)
}

func (x *OrderResponse) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderResponse) GetSide() common.OrderDirection {
	if x != nil {
		return x.Side
	}
	return common.OrderDirection(0)
}

func (x *OrderResponse) GetType() common.OrderType {
	if x != nil {
		return x.Type
	}
	return common.OrderType(0)
}

func (x *OrderResponse) GetTimeInForce() common.OrderTimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return common.OrderTimeInForce(0)
}

func (x *OrderResponse) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *OrderResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderResponse) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *OrderResponse) GetQuantityRemaining() float64 {
	if x != nil {
		return x.QuantityRemaining
	}
	return 0
}

type AllOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderResponse       `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllOrdersResponse) Reset() {
	*x = AllOrdersResponse{}
	mi := &file_port_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllOrdersResponse) ProtoMessage() {}

func (x *AllOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllOrdersResponse.ProtoReflect.Descriptor instead.
func (*AllOrdersResponse) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{8}
}

func (x *AllOrdersResponse) GetOrders() []*OrderResponse {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *AllOrdersResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AllOrdersResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TradePublic struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TradeId        string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	Symbol         string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price          float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity       float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrderTimestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=order_timestamp,json=orderTimestamp,proto3" json:"order_timestamp,omitempty"`
	AggressorSide  common.OrderDirection  `protobuf:"varint,6,opt,name=aggressor_side,json=aggressorSide,proto3,enum=common.OrderDirection" json:"aggressor_side,omitempty"`
	BuyOrderId     string                 `protobuf:"bytes,8,opt,name=buy_order_id,json=buyOrderId,proto3" json:"buy_order_id,omitempty"`
	SellOrderId    string                 `protobuf:"bytes,9,opt,name=sell_order_id,json=sellOrderId,proto3" json:"sell_order_id,omitempty"`
	BuyUserId      string                 `protobuf:"bytes,10,opt,name=buy_user_id,json=buyUserId,proto3" json:"buy_user_id,omitempty"`
	SellUserId     string                 `protobuf:"bytes,11,opt,name=sell_user_id,json=sellUserId,proto3" json:"sell_user_id,omitempty"`
	BuyFee         float64                `protobuf:"fixed64,12,opt,name=buy_fee,json=buyFee,proto3" json:"buy_fee,omitempty"`
	SellFee        float64                `protobuf:"fixed64,13,opt,name=sell_fee,json=sellFee,proto3" json:"sell_fee,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TradePublic) Reset() {
	*x = TradePublic{}
	mi := &file_port_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradePublic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradePublic) ProtoMessage() {}

func (x *TradePublic) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradePublic.ProtoReflect.Descriptor instead.
func (*TradePublic) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{9}
}

func (x *TradePublic) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *TradePublic) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TradePublic) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TradePublic) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TradePublic) GetOrderTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.OrderTimestamp
	}
	return nil
}

func (x *TradePublic) GetAggressorSide() common.OrderDirection {
	if x != nil {
		return x.AggressorSide
	}
	return common.OrderDirection(0)
}

func (x *TradePublic) GetBuyOrderId() string {
	if x != nil {
		return x.BuyOrderId
	}
	return ""
}

func (x *TradePublic) GetSellOrderId() string {
	if x != nil {
		return x.SellOrderId
	}
	return ""
}

func (x *TradePublic) GetBuyUserId() string {
	if x != nil {
		return x.BuyUserId
	}
	return ""
}

func (x *TradePublic) GetSellUserId() string {
	if x != nil {
		return x.SellUserId
	}
	return ""
}

func (x *TradePublic) GetBuyFee() float64 {
	if x != nil {
		return x.BuyFee
	}
	return 0
}

func (x *TradePublic) GetSellFee() float64 {
	if x != nil {
		return x.SellFee
	}
	return 0
}

type TradesPublic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*TradePublic         `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradesPublic) Reset() {
	*x = TradesPublic{}
	mi := &file_port_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradesPublic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradesPublic) ProtoMessage() {}

func (x *TradesPublic) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradesPublic.ProtoReflect.Descriptor instead.
func (*TradesPublic) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{10}
}

func (x *TradesPublic) GetTrades() []*TradePublic {
	if x != nil {
		return x.Trades
	}
	return nil
}

func (x *TradesPublic) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TradesPublic) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PositionPublic struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol            string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	UserId            string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Position          float64                `protobuf:"fixed64,4,opt,name=position,proto3" json:"position,omitempty"`
	MarginAlloc       float64                `protobuf:"fixed64,8,opt,name=margin_alloc,json=marginAlloc,proto3" json:"margin_alloc,omitempty"`
	RealisedPnl       float64                `protobuf:"fixed64,9,opt,name=realised_pnl,json=realisedPnl,proto3" json:"realised_pnl,omitempty"`
	UnrealisedPnl     float64                `protobuf:"fixed64,10,opt,name=unrealised_pnl,json=unrealisedPnl,proto3" json:"unrealised_pnl,omitempty"`
	NetFunding        float64                `protobuf:"fixed64,11,opt,name=net_funding,json=netFunding,proto3" json:"net_funding,omitempty"`
	OpenOrders        float64                `protobuf:"fixed64,12,opt,name=open_orders,json=openOrders,proto3" json:"open_orders,omitempty"`
	OpenQuantity      float64                `protobuf:"fixed64,14,opt,name=open_quantity,json=openQuantity,proto3" json:"open_quantity,omitempty"`
	Leverage          float64                `protobuf:"fixed64,16,opt,name=leverage,proto3" json:"leverage,omitempty"`
	InitialMargin     float64                `protobuf:"fixed64,17,opt,name=initial_margin,json=initialMargin,proto3" json:"initial_margin,omitempty"`
	MaintenanceMargin float64                `protobuf:"fixed64,18,opt,name=maintenance_margin,json=maintenanceMargin,proto3" json:"maintenance_margin,omitempty"`
	AveragePrice      float64                `protobuf:"fixed64,19,opt,name=average_price,json=averagePrice,proto3" json:"average_price,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,99,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PositionPublic) Reset() {
	*x = PositionPublic{}
	mi := &file_port_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionPublic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionPublic) ProtoMessage() {}

func (x *PositionPublic) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionPublic.ProtoReflect.Descriptor instead.
func (*PositionPublic) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{11}
}

func (x *PositionPublic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PositionPublic) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PositionPublic) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PositionPublic) GetPosition() float64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *PositionPublic) GetMarginAlloc() float64 {
	if x != nil {
		return x.MarginAlloc
	}
	return 0
}

func (x *PositionPublic) GetRealisedPnl() float64 {
	if x != nil {
		return x.RealisedPnl
	}
	return 0
}

func (x *PositionPublic) GetUnrealisedPnl() float64 {
	if x != nil {
		return x.UnrealisedPnl
	}
	return 0
}

func (x *PositionPublic) GetNetFunding() float64 {
	if x != nil {
		return x.NetFunding
	}
	return 0
}

func (x *PositionPublic) GetOpenOrders() float64 {
	if x != nil {
		return x.OpenOrders
	}
	return 0
}

func (x *PositionPublic) GetOpenQuantity() float64 {
	if x != nil {
		return x.OpenQuantity
	}
	return 0
}

func (x *PositionPublic) GetLeverage() float64 {
	if x != nil {
		return x.Leverage
	}
	return 0
}

func (x *PositionPublic) GetInitialMargin() float64 {
	if x != nil {
		return x.InitialMargin
	}
	return 0
}

func (x *PositionPublic) GetMaintenanceMargin() float64 {
	if x != nil {
		return x.MaintenanceMargin
	}
	return 0
}

func (x *PositionPublic) GetAveragePrice() float64 {
	if x != nil {
		return x.AveragePrice
	}
	return 0
}

func (x *PositionPublic) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type PositionsPublic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*PositionPublic      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionsPublic) Reset() {
	*x = PositionsPublic{}
	mi := &file_port_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionsPublic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionsPublic) ProtoMessage() {}

func (x *PositionsPublic) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionsPublic.ProtoReflect.Descriptor instead.
func (*PositionsPublic) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{12}
}

func (x *PositionsPublic) GetData() []*PositionPublic {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PositionsPublic) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PositionsPublic) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type BalancePublic struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Deposit          float32                `protobuf:"fixed32,3,opt,name=deposit,proto3" json:"deposit,omitempty"`
	RealisedPnl      float32                `protobuf:"fixed32,4,opt,name=realised_pnl,json=realisedPnl,proto3" json:"realised_pnl,omitempty"`
	OrderMargin      float32                `protobuf:"fixed32,5,opt,name=order_margin,json=orderMargin,proto3" json:"order_margin,omitempty"`
	PositionMargin   float32                `protobuf:"fixed32,6,opt,name=position_margin,json=positionMargin,proto3" json:"position_margin,omitempty"`
	UnrealisedPnl    float32                `protobuf:"fixed32,7,opt,name=unrealised_pnl,json=unrealisedPnl,proto3" json:"unrealised_pnl,omitempty"`
	NetFunding       float32                `protobuf:"fixed32,8,opt,name=net_funding,json=netFunding,proto3" json:"net_funding,omitempty"`
	AvailableBalance float32                `protobuf:"fixed32,9,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	Timestamp        *timestamppb.Timestamp `protobuf:"bytes,99,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BalancePublic) Reset() {
	*x = BalancePublic{}
	mi := &file_port_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalancePublic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalancePublic) ProtoMessage() {}

func (x *BalancePublic) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalancePublic.ProtoReflect.Descriptor instead.
func (*BalancePublic) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{13}
}

func (x *BalancePublic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BalancePublic) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BalancePublic) GetDeposit() float32 {
	if x != nil {
		return x.Deposit
	}
	return 0
}

func (x *BalancePublic) GetRealisedPnl() float32 {
	if x != nil {
		return x.RealisedPnl
	}
	return 0
}

func (x *BalancePublic) GetOrderMargin() float32 {
	if x != nil {
		return x.OrderMargin
	}
	return 0
}

func (x *BalancePublic) GetPositionMargin() float32 {
	if x != nil {
		return x.PositionMargin
	}
	return 0
}

func (x *BalancePublic) GetUnrealisedPnl() float32 {
	if x != nil {
		return x.UnrealisedPnl
	}
	return 0
}

func (x *BalancePublic) GetNetFunding() float32 {
	if x != nil {
		return x.NetFunding
	}
	return 0
}

func (x *BalancePublic) GetAvailableBalance() float32 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *BalancePublic) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type OrdersStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestType:
	//
	//	*OrdersStreamRequest_AddOrder
	//	*OrdersStreamRequest_CancelOrder
	//	*OrdersStreamRequest_ModifyOrder
	RequestType   isOrdersStreamRequest_RequestType `protobuf_oneof:"request_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersStreamRequest) Reset() {
	*x = OrdersStreamRequest{}
	mi := &file_port_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersStreamRequest) ProtoMessage() {}

func (x *OrdersStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersStreamRequest.ProtoReflect.Descriptor instead.
func (*OrdersStreamRequest) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{14}
}

func (x *OrdersStreamRequest) GetRequestType() isOrdersStreamRequest_RequestType {
	if x != nil {
		return x.RequestType
	}
	return nil
}

func (x *OrdersStreamRequest) GetAddOrder() *AddOrderRequest {
	if x != nil {
		if x, ok := x.RequestType.(*OrdersStreamRequest_AddOrder); ok {
			return x.AddOrder
		}
	}
	return nil
}

func (x *OrdersStreamRequest) GetCancelOrder() *CancelOrderRequest {
	if x != nil {
		if x, ok := x.RequestType.(*OrdersStreamRequest_CancelOrder); ok {
			return x.CancelOrder
		}
	}
	return nil
}

func (x *OrdersStreamRequest) GetModifyOrder() *ModifyOrderRequest {
	if x != nil {
		if x, ok := x.RequestType.(*OrdersStreamRequest_ModifyOrder); ok {
			return x.ModifyOrder
		}
	}
	return nil
}

type isOrdersStreamRequest_RequestType interface {
	isOrdersStreamRequest_RequestType()
}

type OrdersStreamRequest_AddOrder struct {
	AddOrder *AddOrderRequest `protobuf:"bytes,1,opt,name=add_order,json=addOrder,proto3,oneof"`
}

type OrdersStreamRequest_CancelOrder struct {
	CancelOrder *CancelOrderRequest `protobuf:"bytes,2,opt,name=cancel_order,json=cancelOrder,proto3,oneof"`
}

type OrdersStreamRequest_ModifyOrder struct {
	ModifyOrder *ModifyOrderRequest `protobuf:"bytes,3,opt,name=modify_order,json=modifyOrder,proto3,oneof"`
}

func (*OrdersStreamRequest_AddOrder) isOrdersStreamRequest_RequestType() {}

func (*OrdersStreamRequest_CancelOrder) isOrdersStreamRequest_RequestType() {}

func (*OrdersStreamRequest_ModifyOrder) isOrdersStreamRequest_RequestType() {}

type CancelAllOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAllOrdersRequest) Reset() {
	*x = CancelAllOrdersRequest{}
	mi := &file_port_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAllOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAllOrdersRequest) ProtoMessage() {}

func (x *CancelAllOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAllOrdersRequest.ProtoReflect.Descriptor instead.
func (*CancelAllOrdersRequest) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{15}
}

func (x *CancelAllOrdersRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

var File_port_proto protoreflect.FileDescriptor

const file_port_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"port.proto\x12\x04port\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"\xe7\x02\n" +
	"\x0fAddOrderRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12*\n" +
	"\x04side\x18\x02 \x01(\x0e2\x16.common.OrderDirectionR\x04side\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.common.OrderTypeR\x04type\x12<\n" +
	"\rtime_in_force\x18\x04 \x01(\x0e2\x18.common.OrderTimeInForceR\vtimeInForce\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12+\n" +
	"\x0fclient_order_id\x18\a \x01(\tH\x00R\rclientOrderId\x88\x01\x01\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB\x12\n" +
	"\x10_client_order_id\"\x86\x01\n" +
	"\x12CancelOrderRequest\x12\x1b\n" +
	"\border_id\x18\x01 \x01(\tH\x00R\aorderId\x12(\n" +
	"\x0fclient_order_id\x18\x02 \x01(\tH\x00R\rclientOrderId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbolB\x11\n" +
	"\x0forder_id_choice\"\xc9\x02\n" +
	"\x12ModifyOrderRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12+\n" +
	"\x11original_quantity\x18\x03 \x01(\x01R\x10originalQuantity\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12*\n" +
	"\x04side\x18\x06 \x01(\x0e2\x16.common.OrderDirectionR\x04side\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12;\n" +
	"\vupdate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"~\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x82\x01\n" +
	"\x12SetLeverageRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bleverage\x18\x02 \x01(\x02R\bleverage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x98\x01\n" +
	"\x0fLeveragesPublic\x122\n" +
	"\tleverages\x18\x01 \x03(\v2\x14.port.LeveragePublicR\tleverages\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xcd\x01\n" +
	"\x0eLeveragePublic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12%\n" +
	"\x0einitial_margin\x18\x03 \x01(\x01R\rinitialMargin\x12-\n" +
	"\x12maintenance_margin\x18\x04 \x01(\x01R\x11maintenanceMargin\x12!\n" +
	"\fmax_position\x18\x05 \x01(\x01R\vmaxPosition\x12\x1a\n" +
	"\bleverage\x18\x06 \x01(\tR\bleverage\"\xdf\x03\n" +
	"\rOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.common.OrderStatusR\x06status\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12*\n" +
	"\x04side\x18\a \x01(\x0e2\x16.common.OrderDirectionR\x04side\x12%\n" +
	"\x04type\x18\b \x01(\x0e2\x11.common.OrderTypeR\x04type\x12<\n" +
	"\rtime_in_force\x18\t \x01(\x0e2\x18.common.OrderTimeInForceR\vtimeInForce\x12;\n" +
	"\vupdate_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12\x17\n" +
	"\auser_id\x18\v \x01(\tR\x06userId\x12&\n" +
	"\x0fclient_order_id\x18\f \x01(\tR\rclientOrderId\x12-\n" +
	"\x12quantity_remaining\x18\r \x01(\x01R\x11quantityRemaining\"\x90\x01\n" +
	"\x11AllOrdersResponse\x12+\n" +
	"\x06orders\x18\x01 \x03(\v2\x13.port.OrderResponseR\x06orders\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\xb2\x03\n" +
	"\vTradePublic\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12C\n" +
	"\x0forder_timestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0eorderTimestamp\x12=\n" +
	"\x0eaggressor_side\x18\x06 \x01(\x0e2\x16.common.OrderDirectionR\raggressorSide\x12 \n" +
	"\fbuy_order_id\x18\b \x01(\tR\n" +
	"buyOrderId\x12\"\n" +
	"\rsell_order_id\x18\t \x01(\tR\vsellOrderId\x12\x1e\n" +
	"\vbuy_user_id\x18\n" +
	" \x01(\tR\tbuyUserId\x12 \n" +
	"\fsell_user_id\x18\v \x01(\tR\n" +
	"sellUserId\x12\x17\n" +
	"\abuy_fee\x18\f \x01(\x01R\x06buyFee\x12\x19\n" +
	"\bsell_fee\x18\r \x01(\x01R\asellFee\"\x89\x01\n" +
	"\fTradesPublic\x12)\n" +
	"\x06trades\x18\x01 \x03(\v2\x11.port.TradePublicR\x06trades\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\x92\x04\n" +
	"\x0ePositionPublic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x01R\bposition\x12!\n" +
	"\fmargin_alloc\x18\b \x01(\x01R\vmarginAlloc\x12!\n" +
	"\frealised_pnl\x18\t \x01(\x01R\vrealisedPnl\x12%\n" +
	"\x0eunrealised_pnl\x18\n" +
	" \x01(\x01R\runrealisedPnl\x12\x1f\n" +
	"\vnet_funding\x18\v \x01(\x01R\n" +
	"netFunding\x12\x1f\n" +
	"\vopen_orders\x18\f \x01(\x01R\n" +
	"openOrders\x12#\n" +
	"\ropen_quantity\x18\x0e \x01(\x01R\fopenQuantity\x12\x1a\n" +
	"\bleverage\x18\x10 \x01(\x01R\bleverage\x12%\n" +
	"\x0einitial_margin\x18\x11 \x01(\x01R\rinitialMargin\x12-\n" +
	"\x12maintenance_margin\x18\x12 \x01(\x01R\x11maintenanceMargin\x12#\n" +
	"\raverage_price\x18\x13 \x01(\x01R\faveragePrice\x128\n" +
	"\ttimestamp\x18c \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x8b\x01\n" +
	"\x0fPositionsPublic\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.port.PositionPublicR\x04data\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xf0\x02\n" +
	"\rBalancePublic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\adeposit\x18\x03 \x01(\x02R\adeposit\x12!\n" +
	"\frealised_pnl\x18\x04 \x01(\x02R\vrealisedPnl\x12!\n" +
	"\forder_margin\x18\x05 \x01(\x02R\vorderMargin\x12'\n" +
	"\x0fposition_margin\x18\x06 \x01(\x02R\x0epositionMargin\x12%\n" +
	"\x0eunrealised_pnl\x18\a \x01(\x02R\runrealisedPnl\x12\x1f\n" +
	"\vnet_funding\x18\b \x01(\x02R\n" +
	"netFunding\x12+\n" +
	"\x11available_balance\x18\t \x01(\x02R\x10availableBalance\x128\n" +
	"\ttimestamp\x18c \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xd9\x01\n" +
	"\x13OrdersStreamRequest\x124\n" +
	"\tadd_order\x18\x01 \x01(\v2\x15.port.AddOrderRequestH\x00R\baddOrder\x12=\n" +
	"\fcancel_order\x18\x02 \x01(\v2\x18.port.CancelOrderRequestH\x00R\vcancelOrder\x12=\n" +
	"\fmodify_order\x18\x03 \x01(\v2\x18.port.ModifyOrderRequestH\x00R\vmodifyOrderB\x0e\n" +
	"\frequest_type\"2\n" +
	"\x16CancelAllOrdersRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols2\xba\x05\n" +
	"\vPortService\x12B\n" +
	"\fStreamOrders\x12\x19.port.OrdersStreamRequest\x1a\x13.port.OrderResponse(\x010\x01\x126\n" +
	"\bGetOrder\x12\x15.port.GetOrderRequest\x1a\x13.port.OrderResponse\x12=\n" +
	"\rGetUserOrders\x12\x13.common.ListRequest\x1a\x17.port.AllOrdersResponse\x12D\n" +
	"\x0fCancelAllOrders\x12\x1c.port.CancelAllOrdersRequest\x1a\x13.common.AckResponse\x121\n" +
	"\vReloadUsers\x12\r.common.Empty\x1a\x13.common.AckResponse\x128\n" +
	"\rGetUserTrades\x12\x13.common.ListRequest\x1a\x12.port.TradesPublic\x12:\n" +
	"\x10GetUserPositions\x12\r.common.Empty\x1a\x15.port.PositionsPublic0\x01\x126\n" +
	"\x0eGetUserBalance\x12\r.common.Empty\x1a\x13.port.BalancePublic0\x01\x12H\n" +
	"\x1aGetAvailableLeverageLevels\x12\x13.common.ListRequest\x1a\x15.port.LeveragesPublic\x12=\n" +
	"\x0fGetUserLeverage\x12\x13.common.ListRequest\x1a\x15.port.LeveragesPublic\x12@\n" +
	"\x0fSetUserLeverage\x12\x18.port.SetLeverageRequest\x1a\x13.common.AckResponseB6\n" +
	"\rcom.qfex.portP\x01Z#github.com/QFEX-org/proto/port;portb\x06proto3"

var (
	file_port_proto_rawDescOnce sync.Once
	file_port_proto_rawDescData []byte
)

func file_port_proto_rawDescGZIP() []byte {
	file_port_proto_rawDescOnce.Do(func() {
		file_port_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_port_proto_rawDesc), len(file_port_proto_rawDesc)))
	})
	return file_port_proto_rawDescData
}

var file_port_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_port_proto_goTypes = []any{
	(*AddOrderRequest)(nil),        // 0: port.AddOrderRequest
	(*CancelOrderRequest)(nil),     // 1: port.CancelOrderRequest
	(*ModifyOrderRequest)(nil),     // 2: port.ModifyOrderRequest
	(*GetOrderRequest)(nil),        // 3: port.GetOrderRequest
	(*SetLeverageRequest)(nil),     // 4: port.SetLeverageRequest
	(*LeveragesPublic)(nil),        // 5: port.LeveragesPublic
	(*LeveragePublic)(nil),         // 6: port.LeveragePublic
	(*OrderResponse)(nil),          // 7: port.OrderResponse
	(*AllOrdersResponse)(nil),      // 8: port.AllOrdersResponse
	(*TradePublic)(nil),            // 9: port.TradePublic
	(*TradesPublic)(nil),           // 10: port.TradesPublic
	(*PositionPublic)(nil),         // 11: port.PositionPublic
	(*PositionsPublic)(nil),        // 12: port.PositionsPublic
	(*BalancePublic)(nil),          // 13: port.BalancePublic
	(*OrdersStreamRequest)(nil),    // 14: port.OrdersStreamRequest
	(*CancelAllOrdersRequest)(nil), // 15: port.CancelAllOrdersRequest
	(common.OrderDirection)(0),     // 16: common.OrderDirection
	(common.OrderType)(0),          // 17: common.OrderType
	(common.OrderTimeInForce)(0),   // 18: common.OrderTimeInForce
	(*timestamppb.Timestamp)(nil),  // 19: google.protobuf.Timestamp
	(common.OrderStatus)(0),        // 20: common.OrderStatus
	(*common.ListRequest)(nil),     // 21: common.ListRequest
	(*common.Empty)(nil),           // 22: common.Empty
	(*common.AckResponse)(nil),     // 23: common.AckResponse
}
var file_port_proto_depIdxs = []int32{
	16, // 0: port.AddOrderRequest.side:type_name -> common.OrderDirection
	17, // 1: port.AddOrderRequest.type:type_name -> common.OrderType
	18, // 2: port.AddOrderRequest.time_in_force:type_name -> common.OrderTimeInForce
	19, // 3: port.AddOrderRequest.timestamp:type_name -> google.protobuf.Timestamp
	16, // 4: port.ModifyOrderRequest.side:type_name -> common.OrderDirection
	19, // 5: port.ModifyOrderRequest.timestamp:type_name -> google.protobuf.Timestamp
	19, // 6: port.ModifyOrderRequest.update_time:type_name -> google.protobuf.Timestamp
	19, // 7: port.GetOrderRequest.timestamp:type_name -> google.protobuf.Timestamp
	19, // 8: port.SetLeverageRequest.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 9: port.LeveragesPublic.leverages:type_name -> port.LeveragePublic
	19, // 10: port.LeveragesPublic.timestamp:type_name -> google.protobuf.Timestamp
	20, // 11: port.OrderResponse.status:type_name -> common.OrderStatus
	16, // 12: port.OrderResponse.side:type_name -> common.OrderDirection
	17, // 13: port.OrderResponse.type:type_name -> common.OrderType
	18, // 14: port.OrderResponse.time_in_force:type_name -> common.OrderTimeInForce
	19, // 15: port.OrderResponse.update_time:type_name -> google.protobuf.Timestamp
	7,  // 16: port.AllOrdersResponse.orders:type_name -> port.OrderResponse
	19, // 17: port.AllOrdersResponse.timestamp:type_name -> google.protobuf.Timestamp
	19, // 18: port.TradePublic.order_timestamp:type_name -> google.protobuf.Timestamp
	16, // 19: port.TradePublic.aggressor_side:type_name -> common.OrderDirection
	9,  // 20: port.TradesPublic.trades:type_name -> port.TradePublic
	19, // 21: port.TradesPublic.timestamp:type_name -> google.protobuf.Timestamp
	19, // 22: port.PositionPublic.timestamp:type_name -> google.protobuf.Timestamp
	11, // 23: port.PositionsPublic.data:type_name -> port.PositionPublic
	19, // 24: port.PositionsPublic.timestamp:type_name -> google.protobuf.Timestamp
	19, // 25: port.BalancePublic.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 26: port.OrdersStreamRequest.add_order:type_name -> port.AddOrderRequest
	1,  // 27: port.OrdersStreamRequest.cancel_order:type_name -> port.CancelOrderRequest
	2,  // 28: port.OrdersStreamRequest.modify_order:type_name -> port.ModifyOrderRequest
	14, // 29: port.PortService.StreamOrders:input_type -> port.OrdersStreamRequest
	3,  // 30: port.PortService.GetOrder:input_type -> port.GetOrderRequest
	21, // 31: port.PortService.GetUserOrders:input_type -> common.ListRequest
	15, // 32: port.PortService.CancelAllOrders:input_type -> port.CancelAllOrdersRequest
	22, // 33: port.PortService.ReloadUsers:input_type -> common.Empty
	21, // 34: port.PortService.GetUserTrades:input_type -> common.ListRequest
	22, // 35: port.PortService.GetUserPositions:input_type -> common.Empty
	22, // 36: port.PortService.GetUserBalance:input_type -> common.Empty
	21, // 37: port.PortService.GetAvailableLeverageLevels:input_type -> common.ListRequest
	21, // 38: port.PortService.GetUserLeverage:input_type -> common.ListRequest
	4,  // 39: port.PortService.SetUserLeverage:input_type -> port.SetLeverageRequest
	7,  // 40: port.PortService.StreamOrders:output_type -> port.OrderResponse
	7,  // 41: port.PortService.GetOrder:output_type -> port.OrderResponse
	8,  // 42: port.PortService.GetUserOrders:output_type -> port.AllOrdersResponse
	23, // 43: port.PortService.CancelAllOrders:output_type -> common.AckResponse
	23, // 44: port.PortService.ReloadUsers:output_type -> common.AckResponse
	10, // 45: port.PortService.GetUserTrades:output_type -> port.TradesPublic
	12, // 46: port.PortService.GetUserPositions:output_type -> port.PositionsPublic
	13, // 47: port.PortService.GetUserBalance:output_type -> port.BalancePublic
	5,  // 48: port.PortService.GetAvailableLeverageLevels:output_type -> port.LeveragesPublic
	5,  // 49: port.PortService.GetUserLeverage:output_type -> port.LeveragesPublic
	23, // 50: port.PortService.SetUserLeverage:output_type -> common.AckResponse
	40, // [40:51] is the sub-list for method output_type
	29, // [29:40] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_port_proto_init() }
func file_port_proto_init() {
	if File_port_proto != nil {
		return
	}
	file_port_proto_msgTypes[0].OneofWrappers = []any{}
	file_port_proto_msgTypes[1].OneofWrappers = []any{
		(*CancelOrderRequest_OrderId)(nil),
		(*CancelOrderRequest_ClientOrderId)(nil),
	}
	file_port_proto_msgTypes[14].OneofWrappers = []any{
		(*OrdersStreamRequest_AddOrder)(nil),
		(*OrdersStreamRequest_CancelOrder)(nil),
		(*OrdersStreamRequest_ModifyOrder)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_port_proto_rawDesc), len(file_port_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_port_proto_goTypes,
		DependencyIndexes: file_port_proto_depIdxs,
		MessageInfos:      file_port_proto_msgTypes,
	}.Build()
	File_port_proto = out.File
	file_port_proto_goTypes = nil
	file_port_proto_depIdxs = nil
}
